### ISSUE TITLE
JWLMerge crashes when importing Bible notes

### ISSUE THREAD

**Issue by temporarium** [AntonyCorbett/JWLMerge#12]
![sshot-1](https://user-images.githubusercontent.com/4754345/52728267-f25ed300-2f84-11e9-85f7-fc5608ca886a.jpg)

So, I've tried to import some notes on Genesis and the app crashes. I limited to file to only a handful of notes (see attachment), thinking that maybe the file was too large (my Genesis notes are over 2,000 lines).

Any idea what is wrong? Are the notes too long? Do the lines have to have a line-break after x number of characters?

This is my notes file:
```
[BibleKeySymbol=Rbi8]
[MepsLanguageId=1]

[1:1:1]
Dios

en las Escrituras Hebreas la palabra *’elóh·ah* (dios) tiene dos formas plurales, a saber, *’elo·hím* (dioses) y *’elo·héh* (dioses de); por lo general estas formas plurales aluden a Jehová, y en ese caso se traducen en singular, "Dios"; en *A Dictionary of the Bible*, William Smith dice: "La caprichosa idea de que [*’elo·hím*] se refería a la trinidad de personas en la Deidad difícilmente cuenta ahora con apoyo entre los eruditos. Es o lo que los gramáticos llaman el plural mayestático, o denota la plenitud de fortaleza divina, la suma de los poderes que Dios despliega"; *The American Journal of Semitic Languages and Literatures* dice de *’elo·hím*: "Se construye casi invariablemente con un predicado verbal en singular, y toma un atributo adjetival en singular"; para ilustrar esto, el título *’elo·hím* aparece 35 veces por sí solo en el relato de la creación, y en cada ocasión el verbo que describe lo que Dios dijo e hizo está en singular; por eso, esa revista llega a esta conclusión: "[*’Elo·hím*] tiene que ser explicado más bien como un plural intensivo, que denota grandeza y majestad";

el griego no tiene un ‘plural de majestad o excelencia’; por consiguiente, en Gén 1:1 los traductores de la LXX usaron *ho The·os´* (Dios, en singular) como el equivalente de *’Elo·him´*

[1:1:1]
principio

el universo fue creado mucho antes del primer día

[1:1:2]
la fuerza activa de Dios se movía

los vocablos bíblicos (en griego y hebreo) que se traducen por "espíritu" pueden verterse en otros contextos "viento", "ráfaga", "soplo" y "aliento"; según los lexicógrafos, estos términos originales transmiten la idea de una fuerza dinámica invisible; el espíritu santo, igual que el aire en movimiento, escapa al ojo humano, pero sus efectos son reales y perceptibles;

en 1879, el biblista Charles L. Ives ilustró con maestría la capacidad que Dios tiene de ejercer su poder desde el lugar que ocupa: "Por ejemplo, nosotros decimos: ‘Abre las contraventanas para que entre el sol en la habitación’. No nos referimos al cuerpo celeste, el Sol, sino a la radiación solar, los rayos procedentes del Sol"; así mismo, Dios no tiene que viajar a cada sitio donde va a usar su fuerza activa; sencillamente se vale de su espíritu santo, con el que puede alcanzar hasta los puntos más lejanos de su creación

[1:1:2]
oscuridad

algo, quizá una mezcla de vapor de agua, otros gases y polvo volcánico, debió impedir que la luz del Sol llegara hasta la superficie de la Tierra

[1:1:3]
llegó a haber luz

esta luz provenía del Sol, pero el Sol mismo no podría divisarse a través de la nubosidad; por eso, la luz que llegaba a la Tierra era "luz difusa"; la intensidad de la luz que penetró hasta la superficie terrestre fue aumentando, y ese proceso continuó en el futuro; "gradualmente llegó a" - expresión que refleja con exactitud un estado del verbo hebreo que denota una acción progresiva que tarda un tiempo en completarse; todo el que lea el primer capítulo de Génesis en hebreo puede hallar unas cuarenta veces esta forma, la cual es un factor clave para la comprensión de dicho capítulo; lo que Dios empezó en la tarde figurativa de un período creativo se hizo progresivamente claro o evidente en la mañana de ese "día"; por otra parte, lo que se empezaba en un período no tenía que estar completamente terminado antes de comenzar el siguiente período; así que, el primer día, una luz opaca llegó a la superficie terrestre; la atmósfera de la Tierra debió aclararse en el cuarto "día", de modo que llegaría más luz del Sol y de otros cuerpos celestes a la Tierra
```
![sshot-2](https://user-images.githubusercontent.com/4754345/52728687-bed07880-2f85-11e9-98e9-8d989cd44575.jpg)
![sshot-3](https://user-images.githubusercontent.com/4754345/52728688-bed07880-2f85-11e9-995d-e1b1f303784e.jpg)

**Comment by AntonyCorbett** [comment]
@temporarium Sorry, I have omitted some code from the build. Will fix asap.

**Comment by temporarium** [comment]
Ah, ok. Had me worried for a bit :-)
Thank you for making it available!

**Comment by AntonyCorbett** [comment]
@temporarium Fixed in latest pre-release, but still in need of rigorous testing!

**Comment by temporarium** [comment]
Just tried with 1.0.0.22. Still the same behaviour. I even get an error/crash trying to import your sample notes.

**Comment by AntonyCorbett** [comment]
Please try again with build 23. If it fails again please would you let me have a copy of the log file (Documents\JWLMerge\Logs). Thanks.

**Comment by temporarium** [comment]
Well, at least it doesn't crash :-)
I tried importing your notes:
```
[BibleKeySymbol=nwtsty]
[MepsLanguageId=0]

[1:3:15]
First Prophecy

A prophecy. A covenant. The brevity and symbolic language of the 
statement left many questions unanswered!

[1:3:15:4:4:0]
Enmity

There was also enmity on the part of the woman toward the Serpent. 
Satan had called into question the integrity of every one of God's 
intelligent creatures, including all the angels ... they could not 
do otherwise than feel a loathing toward him.
```
Something gets added, as seen from the screenshots:

![sshot-1](https://user-images.githubusercontent.com/4754345/52739617-4eceec00-2f9f-11e9-9874-50f0e326a295.jpg)
![sshot-2](https://user-images.githubusercontent.com/4754345/52739618-4eceec00-2f9f-11e9-8c7b-382bab8c12cd.jpg)

However, it doesn't seem to be saved or written to the .jwlibrary file. Once I reopen it in JWLMerge, there is no evidence of those notes...

When I try to import mine, nothing happens.



[log.txt](https://github.com/AntonyCorbett/JWLMerge/files/2861966/log.txt)

**Comment by AntonyCorbett** [comment]
@temporarium Thanks for feedback. I can't reproduce this - all works ok here. I will add some more logging entries

**Comment by temporarium** [comment]
I'm getting mixed results. I was able to import a simple test file, but it doesn't work with my notes file.

Does the encoding of the text file matter? ANSI or UTF?

Are you able to import my file? Is it laid out/formatted correctly?
[test.txt](https://github.com/AntonyCorbett/JWLMerge/files/2873714/test.txt)

**Comment by AntonyCorbett** [comment]
@temporarium Yes, I can successfully import your test.txt file. It is Ansi encoded so some of the characters are not supported (but still imports ok). Change it to UTF-8 and the characters are reproduced as they should be.

**Comment by temporarium** [comment]
Thank you for letting me know that. So, it must be on my end... perhaps my .jwlibrary file? I would send it to you to have a look, but via a more private medium only.
I'm on Windows 7x64. What else could be throwing a wrench into this?

**Comment by AntonyCorbett** [comment]
@temporarium Please email me your backup file to the following address:

help at soundbox.on.spiceworks.com

**Comment by AntonyCorbett** [comment]
@temporarium I've received your file and can reproduce your problem. I'll let you know as soon I have investigated. Thanks for your help.

**Comment by AntonyCorbett** [comment]
@temporarium The problem arises when you have existing notes that refer to a highlighted section that extends over a verse boundary. I will fix.

**Comment by AntonyCorbett** [comment]
@temporarium Please would you test the latest pre-release?

**Comment by temporarium** [comment]
Excellent! I'm importing OK now. Thank you!

Just wondering: is there any way to tag the imported notes somehow?

**Comment by temporarium** [comment]
Another question: is the 50-character limit for the titles set in stone, or is there a possibility you could remove it, perhaps taking every first line as note title?

**Comment by AntonyCorbett** [comment]
Perhaps we need to take a step back and analyse requirements further. It may be that a more flexible file format (or even a common open format) for import would be better

**Comment by temporarium** [comment]
Wow, that's som write-up on the formats!!

I would love to see mark-up implemented in the comments, but I guess that will have to be implemented on the app itself, right?

Anyway, you know much better than I do how these notes are stored in the jwlibrary file - specifically how the tags are stored. As for importing, it could be as simple as implementing a title line for each note enclosed in {{}}, which could in addition include a comma-separated list of tags? Something like: {{First Prophecy|Prophecy,Genesis}}

I'm happy to do the testing for you :-)

**Comment by AntonyCorbett** [comment]
> Wow, that's some write-up on the formats!!

Yes. Not mine, I hasten to add. But a useful resource, and interesting reading.

**Comment by temporarium** [comment]
Did you change/update something in 1.0.0.24?

**Comment by AntonyCorbett** [comment]
@temporarium would you mind creating new issues for any ongoing questions / problems (i.e. one issue per question) please? It will help me not to forget items. Thanks.
